default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: 1234
  host: 127.0.0.1
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: wkm-rest-api

#
# test:
#   <<: *default
#   database: rest_api_test

# production:
#   <<: *default
#   database: wkm-rest-api-pŕod
